export const ORANGE = "#c05621";
export const CREAM = "#faf6f0";
export const INK = "#2b2118";
export const MUTE = "#8a7d6f";
export const BORDER = "#ece3d6";

export const styles = {
  appShell: {
    minHeight: "100vh",
    background: CREAM,
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    display: "flex",
    flexDirection: "column",
  },
  topNav: {
    position: "sticky",
    top: 0,
    zIndex: 20,
    background: "rgba(250,246,240,0.92)",
    backdropFilter: "blur(8px)",
    borderBottom: `1px solid ${BORDER}`,
  },
  topNavInner: {
    maxWidth: 1160,
    margin: "0 auto",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 20,
  },
  brand: { display: "flex", alignItems: "center", gap: 8, cursor: "pointer" },
  brandMark: {
    width: 30,
    height: 30,
    borderRadius: 8,
    background: ORANGE,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 15,
  },
  brandName: { fontWeight: 800, fontSize: 18, color: INK, letterSpacing: -0.3 },
  navLinks: { display: "flex", gap: 28, flex: 1, justifyContent: "center" },
  navLink: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: 14,
    fontWeight: 700,
    padding: "6px 0",
    textDecoration: "none",
  },
  publishBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: ORANGE,
    color: "#fff",
    border: "none",
    borderRadius: 10,
    padding: "10px 16px",
    fontWeight: 700,
    fontSize: 13.5,
    cursor: "pointer",
    whiteSpace: "nowrap",
    textDecoration: "none",
  },
  menuBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    border: `1px solid ${BORDER}`,
    background: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  mobileMenu: { padding: "0 20px 16px" },
  mobileMenuPublish: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    background: ORANGE,
    color: "#fff",
    border: "none",
    borderRadius: 12,
    padding: "12px 0",
    fontWeight: 700,
    fontSize: 14,
    cursor: "pointer",
    textDecoration: "none",
  },
  main: { flex: 1 },
  page: { maxWidth: 1160, margin: "0 auto", padding: "24px 20px 80px" },
  pageHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
    flexWrap: "wrap",
    gap: 12,
  },
  hero: { padding: "12px 0 28px", maxWidth: 680 },
  eyebrow: { margin: 0, fontSize: 11, fontWeight: 800, letterSpacing: 1.5, color: ORANGE },
  h1: { margin: "6px 0 10px", fontWeight: 800, color: INK, letterSpacing: -0.5, lineHeight: 1.15 },
  heroSub: { margin: "0 0 20px", fontSize: 14.5, color: MUTE, lineHeight: 1.6, maxWidth: 480 },
  searchBar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "#fff",
    border: `1px solid ${BORDER}`,
    borderRadius: 14,
    padding: "13px 16px",
    maxWidth: 480,
    boxShadow: "0 2px 10px rgba(43,33,24,0.04)",
  },
  searchInput: {
    border: "none",
    outline: "none",
    background: "transparent",
    fontSize: 14.5,
    flex: 1,
    color: INK,
    fontFamily: "inherit",
  },
  resultsHeader: { marginBottom: 12 },
  resultCount: { margin: 0, fontSize: 13, color: MUTE, fontWeight: 700 },
  list: { display: "flex", flexDirection: "column", gap: 12 },
  gridDesktop: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: 16,
  },
  card: {
    display: "flex",
    gap: 12,
    background: "#fff",
    border: `1px solid ${BORDER}`,
    borderRadius: 16,
    padding: 12,
    cursor: "pointer",
    textDecoration: "none",
  },
  cardEmoji: {
    width: 64,
    height: 64,
    borderRadius: 12,
    background: "#f3e9dc",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 30,
    flexShrink: 0,
  },
  cardTitle: { margin: 0, fontSize: 14.5, fontWeight: 800, color: INK },
  cardPrice: { margin: 0, fontSize: 13, fontWeight: 800, color: ORANGE, whiteSpace: "nowrap" },
  cardMeta: { display: "flex", alignItems: "center", gap: 4, fontSize: 11.5, color: MUTE, marginTop: 3 },
  cardTags: { display: "flex", gap: 6, marginTop: 8, flexWrap: "wrap" },
  tag: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    fontWeight: 600,
    color: MUTE,
    background: "#f3ede2",
    padding: "3px 7px",
    borderRadius: 8,
  },
  tagStar: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    fontSize: 10.5,
    fontWeight: 700,
    color: ORANGE,
    background: "#fbeee2",
    padding: "3px 7px",
    borderRadius: 8,
  },
  emptyState: { textAlign: "center", padding: "60px 20px", color: INK, gridColumn: "1 / -1" },
  backLink: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    color: MUTE,
    fontWeight: 700,
    fontSize: 13.5,
    cursor: "pointer",
    padding: "0 0 18px",
    marginTop: -4,
    textDecoration: "none",
  },
  heroPhoto: {
    height: 260,
    borderRadius: 18,
    background: "linear-gradient(135deg,#f3e9dc,#e9d9c2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 90,
  },
  specRow: { display: "flex", gap: 10, margin: "18px 0" },
  specBox: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    background: "#fff",
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    padding: "12px 4px",
    fontSize: 11.5,
    fontWeight: 700,
    color: INK,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 0.5,
    color: MUTE,
    textTransform: "uppercase",
    margin: "20px 0 8px",
  },
  paragraph: { fontSize: 14, lineHeight: 1.65, color: "#4a4038", margin: 0 },
  conditionsBox: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    background: "#fbeee2",
    border: "1px solid #f0d8c0",
    borderRadius: 14,
    padding: 16,
  },
  conditionRow: { display: "flex", gap: 10, alignItems: "flex-start" },
  conditionLabel: { margin: 0, fontSize: 12, fontWeight: 800, color: INK },
  conditionText: { margin: "2px 0 0", fontSize: 13, lineHeight: 1.5, color: "#4a4038" },
  checkboxRow: { display: "flex", alignItems: "center", gap: 9, padding: "10px 2px", cursor: "pointer", marginBottom: 6 },
  checkbox: { width: 18, height: 18, accentColor: ORANGE, cursor: "pointer" },
  ownerRow: { display: "flex", alignItems: "center", gap: 10 },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: "50%",
    background: ORANGE,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 17,
  },
  avatarBig: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    background: ORANGE,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 20,
  },
  contactRow: { display: "flex", gap: 12, marginTop: 26 },
  contactBtn: {
    flex: 1,
    maxWidth: 220,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "14px 0",
    borderRadius: 14,
    fontWeight: 800,
    fontSize: 14.5,
    textDecoration: "none",
    cursor: "pointer",
  },
  contactBtnOutline: { border: `2px solid ${ORANGE}`, color: ORANGE, background: "#fff" },
  contactBtnFill: { border: "2px solid #25D366", color: "#fff", background: "#25D366" },
  formCard: { background: "#fff", border: `1px solid ${BORDER}`, borderRadius: 18, padding: 22 },
  primaryBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "14px 0",
    borderRadius: 14,
    border: "none",
    background: ORANGE,
    color: "#fff",
    fontWeight: 800,
    fontSize: 15,
    cursor: "pointer",
  },
  primaryBtnSmall: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    margin: "0 auto",
    padding: "10px 16px",
    borderRadius: 12,
    border: "none",
    background: ORANGE,
    color: "#fff",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    textDecoration: "none",
  },
  photoPicker: {
    height: 100,
    border: `2px dashed ${ORANGE}`,
    borderRadius: 14,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginBottom: 18,
    background: "#fbeee2",
    cursor: "pointer",
  },
  label: { display: "block", fontSize: 11.5, fontWeight: 700, color: MUTE, marginBottom: 6 },
  input: {
    width: "100%",
    boxSizing: "border-box",
    border: `1px solid ${BORDER}`,
    borderRadius: 11,
    padding: "11px 13px",
    fontSize: 13.5,
    color: INK,
    outline: "none",
    fontFamily: "inherit",
    background: "#fff",
  },
  profileCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    background: "#fff",
    border: `1px solid ${BORDER}`,
    borderRadius: 16,
    padding: 16,
    marginBottom: 8,
  },
  roleToggle: { display: "flex", gap: 8, marginBottom: 4, maxWidth: 320 },
  roleBtn: {
    flex: 1,
    padding: "10px 0",
    borderRadius: 12,
    border: `1px solid ${BORDER}`,
    background: "#fff",
    fontWeight: 700,
    fontSize: 13,
    color: MUTE,
    cursor: "pointer",
  },
  roleBtnActive: { background: ORANGE, color: "#fff", border: `1px solid ${ORANGE}` },
  settingRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "14px 4px",
    borderBottom: `1px solid ${BORDER}`,
    maxWidth: 420,
  },
  tabBar: {
    position: "sticky",
    bottom: 0,
    display: "flex",
    borderTop: `1px solid ${BORDER}`,
    background: CREAM,
    padding: "8px 0 14px",
    zIndex: 20,
  },
  tabBtn: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "4px 0",
  },
  toast: {
    position: "fixed",
    bottom: 90,
    left: "50%",
    transform: "translateX(-50%)",
    background: INK,
    color: "#fff",
    padding: "10px 18px",
    borderRadius: 30,
    fontSize: 12.5,
    fontWeight: 700,
    boxShadow: "0 8px 24px rgba(0,0,0,0.25)",
    whiteSpace: "nowrap",
    zIndex: 30,
  },
};
